name: mobile_app
description: Smart Farming Mobile Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ðŸ”¥ Backend Integration
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7

  # ðŸ” Google Sign-In
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
